---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - resources/namespace.yaml
  - resources/realopinsight-config.yaml
  - resources/realopinsight-rbac.yaml
  - resources/realopinsight-app.yaml
  - resources/realopinsight-tests.yaml
images:
  - name: realopinsight
    newName: rchakode/realopinsight
    newTag: 23.09.0
