.TH ngrt4n 1  "Juin 08, 2012" "version 2.0" "USER COMMANDS"
.SH NAME
ngrt4n \- the client module of NGRT4N.
.SH SYNOPSIS
.B ngrt4n
[OPTIONS]
.SH DESCRIPTION
This program allows to run the client GUI utilities of NGRT4N. 
.PP
It sits on users' workstations and interact with the broker module (ngrt4nd) over a zmq-based messaging system.
.SH OPTIONS
.TP
\-c
Launches the configuration utility that allows to set monitoring settings or change your password.
.TP
\-e [config] 
Launches the Editor utility GUI while loading the given configure file, if specified.
.TP
\-d <config>
Launches the Operator Console (OC) GUI while loading the given configuration file.
.TP
\-v
Prints the version plus license information and exits the program.
.TP
\-h
Prints a summary of the command-line usage and exits the program.
.SH EXAMPLES
.TP
ngrt4n -d examples/hosting-platform.xml
.TP
Launch the OC utility while loading the configuration file examples/hosting-platform.xml from the current directory.
.SH AUTHOR
Rodrigue Chakode <rodrigue.chakode@ngrt4n.com>
.SH COPYRIGHT
NGRT4N (http://ngrt4n.com) is a free software released under the terms of GNU GPL-v3 license.
.SH SEE ALSO
.BR ngrt4n(1)

