#!/bin/bash

TARGET_VERSION=2014b3
PATCH_TARBALL=patch_${TARGET_VERSION}.tar.gz
REALOPINSIGHT_PREFIX=/opt
REALOPINSIGHT_WWW=/var/www
REALOPINSIGHT_WWW_USER=www-data 
REALOPINSIGHT_WWW_GROUP=www-data

tar --same-owner zcf ${PATCH_TARBALL} ${REALOPINSIGHT_WWW}/realopinsight
